name: CDK deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # change this to the correct python version you are using

    - name: Install dependencies
      run: |
        npm install -g aws-cdk && \
        python -m pip install --upgrade pip && \
        pip install projen && \
        pip list && \
        projen && \
        source .venv/bin/activate && \
        pip list

    - name: Deploy to AWS
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEPLOYMENT_ACCOUNT_ID: ${{ secrets.AWS_DEPLOYMENT_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PINECONE_DB_API_KEY_SECRET_NAME: ${{ secrets.PINECONE_DB_API_KEY_SECRET_NAME }}
        PINECONE_DB_ENVIRONMENT: ${{ secrets.PINECONE_DB_ENVIRONMENT }}
      run: |
        source .venv/bin/activate && \
        export PATH=.venv/bin:$PATH && \
        cdk deploy --all --require-approval never
