name: CDK Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Cache the .venv directory
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('.projenrc.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('.projenrc.py') }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # change this to the correct python version you are using
      
    - name: Install dependencies
      run: |
        npm install -g aws-cdk && \
        python -m pip install --upgrade pip && \
        pip install projen && \
        projen && \
        source .venv/bin/activate && \
        pip list

    - name: Run Tests
      run: |
        source .venv/bin/activate && \
        export PATH=.venv/bin:$PATH && \
        make test
    - name: Deploy to AWS
      env:
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ vars.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        PINECONE_DB_ENVIRONMENT: ${{ vars.PINECONE_DB_ENVIRONMENT }}
        AWS_DEPLOYMENT_ACCOUNT_ID: '645860363137'
        DEPLOYMENT_TYPE: 'dev'
        PINECONE_DB_API_KEY_SECRET_NAME: 'dev/tai_service/pinecone_db/api_key'
        DOC_DB_READ_ONLY_USER_PASSWORD_SECRET_NAME: 'dev/tai_service/document_DB/read_ONLY_user_password'
        DOC_DB_READ_WRITE_USER_PASSWORD_SECRET_NAME: 'dev/tai_service/document_DB/read_write_user_password'
        DOC_DB_ADMIN_USER_PASSWORD_SECRET_NAME: 'dev/tai_service/document_DB/admin_password'
      run: |
        source .venv/bin/activate && \
        export PATH=.venv/bin:$PATH && \
        make deploy-all
