name: CDK Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space

      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Validate Device Free Space
      run: |
        echo "Free space:"
        df -h

    - name: Checkout code
      uses: actions/checkout@v2

    # Cache the .venv directory
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # change this to the correct python version you are using
      
    - name: Install dependencies
      run: |
        npm install -g aws-cdk && \
        python -m pip install --upgrade pip && \
        pip install projen && \
        projen && \
        source .venv/bin/activate && \
        pip list

    - name: Run Tests
      run: |
        source .venv/bin/activate && \
        export PATH=.venv/bin:$PATH && \
        make full-test

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      run: |
        make ecr-docker-login REGION=$AWS_DEFAULT_REGION ACCOUNT_ID=$AWS_DEPLOYMENT_ACCOUNT_ID && \
        source .venv/bin/activate && \
        export PATH=.venv/bin:$PATH && \
        make deploy-all
